name: .NET

on:
  push:
    branches: [ 'master', 'development' ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Ixian-DLT
      uses: actions/checkout@v2

    - name: Checkout Ixian-Core
      uses: actions/checkout@v2
      with:
        repository: ProjectIxian/Ixian-Core
        path: Ixian-Core
        ref: ${{ github.event.push.ref }}

    - name: Restore dependencies
      run: nuget restore DLTNode.sln

    - name: Build
      run: msbuild DLTNode.sln

    - name: Test
      run: msbuild test --no-build --verbosity normal
